{
    "th06 Bomb Reimu A": "Знак духу \"Печатка фантазії\"",
    "th06 Bomb Reimu B": "Знак мрії \"Круг запечатування зла\"",
    "th06 Bomb Marisa A": "Знак магії \"Мрія зоряного пилу\"",
    "th06 Bomb Marisa B": "Знак любові \"Майстер Спарк\"",
    "th06 up": "Вгору",
    "th06 down": "Вниз",
    "th06 left": "Направо",
    "th06 right": "Наліво",
    "th06 vertex": "Не використовувати буфер вершин",
    "th06 fog": "Не використовувати туман",
    "th06 16bit textures": "16-бітні текстури",
    "th06 Gouraud shading": "Подавити використання метода тонування Гуро",
    "th06 color composition": "Змішування кольорів не відноситься до текстур",
    "th06 rasterizer mode": "Запускатися в режимі Reference Rasterizer",
    "th06 clear buffer": "Очищувати Back buffer при оновленні",
    "th06 minimum graphics": "Показувати мінімум графіки",
    "th06 depth test": "Вимкнути тест глибини",
    "th06 force frame": "Вимушено використовувати 60 к/с",
    "th06 fullscreen": "На весь екран",
    "th06 windowed": "У вікні",
    "th06 full rate": "1/1 (за замовчуванням)",
    "th06 half rate": "1/2",
    "th06 third rate": "1/3",
    "th06 32bits mode": "32 біт",
    "th06 16bits mode": "16 біт",
    "th06 accept": "ОК",
    "th06 cancel": "Відміна",
    "th06 screen mode": "Режим екрана",
    "th06 refresh rate": "Пропуск кадрів",
    "th06 colors": "Кольоровий режим",
    "th06 pad X axis": "Вісь X (1~1000)",
    "th06 pad Y axis": "Вісь Y (1~1000)",
    "th06 check pad": "Перевіряти введення клавіатури",
    "th06 DirectInput": "Не використовувати DirectInput",
    "th06 config saved caption": "ОК",
    "th06 config saved text": "Налаштування збережено.",
    "Stats Time Since Startup": "Час з запуску",
    "Stats Total Playtime": "Час гри",
    "Stats Play Count": "Разів зіграно",
    "Stats Clear Count": "Разів пройдено",
    "Stats Continue": "Продовження",
    "Stats Practice": "Практика",
    "Stats Retries": "Спроб",
    "DirectInput fix": "Використовувати DirectInput",
    "DirectInput fix, layout-dependent shot key": "Використовувати DirectInput (Клавіша пострілу: %c)",
    "th06": "(Тохо Комакьо) Східні землі червоної дияволиці ~ Втілення Червоної дияволиці",
    "th06 Stats ReimuA": "Рейму Хакурей (Дух)",
    "th06 Stats ReimuB": "Рейму Хакурей (Мрія)",
    "th06 Stats MarisaA": "Маріса Кірісаме (Магія)",
    "th06 Stats MarisaB": "Маріса Кірісаме (Любов)",
}